### ISSUE TITLE
Error run Arjun

### ISSUE THREAD

**Issue by tXambe** [s0md3v/Arjun#110]
Hello,

When I run Arjun script I have this error:

```
[~] Performing heuristic level checks
Traceback (most recent call last):
  File "/opt/API/Arjun/arjun.py", line 248, in <module>
    finalResult[url] = initialize(url, include, headers, GET, delay, paramList, threadCount)
  File "/opt/API/Arjun/arjun.py", line 222, in initialize
    toBeChecked = narrower(toBeChecked, url, include, headers, GET, delay, originalResponse, originalCode, reflections, factors, threadCount)
  File "/opt/API/Arjun/arjun.py", line 172, in narrower
    if result.result():
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/API/Arjun/arjun.py", line 145, in quickBruter
    newResponse = requester(url, joined, headers, GET, delay, proxies)
  File "/opt/API/Arjun/core/requester.py", line 20, in requester
    response = requests.get(url, params=data, headers=headers, verify=False, proxies=proxies)
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

```
Anyone can help me ?

A greeting and thanks

**Comment by s0md3v** [comment]
Are you using the latest build? Because this issue has been fixed already.

**Comment by s0md3v** [comment]
Closing due to inactivity, feel free to re-open if you can reproduce the error on the latest build.
