### ISSUE TITLE
import error from burpsuite 

### ISSUE THREAD

**Issue by mohammed-sec2010** [s0md3v/Arjun#116]
command :  arjun  -i /opt/paramters/Arjun2/Arjun2/Arjun/1/test3

output: 
    _
   /_| _ '
  (  |/ /(//) v2.1.0
      _/      

Traceback (most recent call last):
  File "/usr/local/bin/arjun", line 33, in <module>
    sys.exit(load_entry_point('arjun==2.1.0', 'console_scripts', 'arjun')())
  File "/usr/local/lib/python3.8/site-packages/arjun-2.1.0-py3.8.egg/arjun/__main__.py", line 151, in main
    request = prepare_requests(args)
  File "/usr/local/lib/python3.8/site-packages/arjun-2.1.0-py3.8.egg/arjun/core/utils.py", line 277, in prepare_requests
    return importer(args.import_file, mem.var['method'], headers, args.include)
  File "/usr/local/lib/python3.8/site-packages/arjun-2.1.0-py3.8.egg/arjun/core/importer.py", line 97, in importer
    return burp_import(path)
  File "/usr/local/lib/python3.8/site-packages/arjun-2.1.0-py3.8.egg/arjun/core/importer.py", line 49, in burp_import
    request = parse_request(match.group(4))
  File "/usr/local/lib/python3.8/site-packages/arjun-2.1.0-py3.8.egg/arjun/core/importer.py", line 23, in parse_request
    result['headers'] = parse_headers(match.group(3))
NameError: name 'parse_headers' is not defined

**Comment by mohammed-sec2010** [comment]
it is not working bro

result :
Traceback (most recent call last):
  File "/usr/local/bin/arjun", line 33, in <module>
    sys.exit(load_entry_point('arjun==2.1.0', 'console_scripts', 'arjun')())
  File "/usr/local/bin/arjun", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/arjun-2.1.0-py3.8.egg/arjun/__main__.py", line 11, in <module>
    from arjun.core.bruter import bruter
  File "/usr/local/lib/python3.8/site-packages/arjun-2.1.0-py3.8.egg/arjun/core/bruter.py", line 3, in <module>
    from arjun.core.anomaly import compare
  File "/usr/local/lib/python3.8/site-packages/arjun-2.1.0-py3.8.egg/arjun/core/anomaly.py", line 3, in <module>
    from arjun.core.utils import lcs, diff_map, remove_tags
  File "/usr/local/lib/python3.8/site-packages/arjun-2.1.0-py3.8.egg/arjun/core/utils.py", line 11, in <module>
    from arjun.core.importer import importer
  File "/usr/local/lib/python3.8/site-packages/arjun-2.1.0-py3.8.egg/arjun/core/importer.py", line 3, in <module>
    from arjun.core.utils import parse_headers
ImportError: cannot import name 'parse_headers' from partially initialized module 'arjun.core.utils' (most likely due to a circular import) (/usr/local/lib/python3.8/site-packages/arjun-2.1.0-py3.8.egg/arjun/core/utils.py)

**Comment by s0md3v** [comment]
It should work now, if it doesn't. I will fix it properly later in the day.

**Comment by mohammed-sec2010** [comment]
it is working now thanks :)
