### ISSUE TITLE
export error to burpsuite 

### ISSUE THREAD

**Issue by mohammed-sec2010** [s0md3v/Arjun#117]
command: arjun -i /home/ali/main/test5 -c 250 -oB 127.0.0.1:8080 

output : 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 598, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 319, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /?hidden=111110&443=111111&beacon=111112&target=111113&atts=111114&mbname=111115&nocache=111116&promocodeaction=111117&ee=111118&number=111119&email=111110&page_type=111111&Soups=111112&fileEdit=111113&crt=111114&xml=111115&p=111116&msg1=111117&proxyurl=111118&page=111119&minutes=111120&pageid=111121 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/arjun", line 33, in <module>
    sys.exit(load_entry_point('arjun==2.1.0', 'console_scripts', 'arjun')())
  File "/usr/local/lib/python3.8/site-packages/arjun-2.1.0-py3.8.egg/arjun/__main__.py", line 186, in main
    exporter(final_result)
  File "/usr/local/lib/python3.8/site-packages/arjun-2.1.0-py3.8.egg/arjun/core/exporter.py", line 57, in exporter
    burp_export(result)
  File "/usr/local/lib/python3.8/site-packages/arjun-2.1.0-py3.8.egg/arjun/core/exporter.py", line 24, in burp_export
    requests.get(url, params=populate(data['params']), headers=data['headers'])
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /?hidden=111110&443=111111&beacon=111112&target=111113&atts=111114&mbname=111115&nocache=111116&promocodeaction=111117&ee=111118&number=111119&email=111110&page_type=111111&Soups=111112&fileEdit=111113&crt=111114&xml=111115&p=111116&msg1=111117&proxyurl=111118&page=111119&minutes=111120&pageid=111121 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)')))

**Comment by maffbowers** [comment]
I can't get exporting to Burpsuite to work at all - at the Burpsuite end I get "Invalid client request received: Dropped request looping back to same Proxy listener". I'm using port 8081 as an invisible listener on Burp after the original port 8080 listener wasn't working but even the invisible listener isn't picking up the Burp export out of Arjun. I'm using -**oB 127.0.0.1:8081** as the export option

**Comment by maffbowers** [comment]
> command: arjun -i /home/ali/main/test5 -c 250 -oB 127.0.0.1:8080
> 
> output :
> Traceback (most recent call last):
> File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 598, in urlopen
> httplib_response = self._make_request(conn, method, url,
> File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 346, in _make_request
> self._validate_conn(conn)
> File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn conn.connect() File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 319, in connect self.sock = ssl_wrap_socket( File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
> return context.wrap_socket(sock, server_hostname=server_hostname)
> File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
> return self.sslsocket_class._create(
> File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
> self.do_handshake()
> File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
> self._sslobj.do_handshake()
> ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
> resp = conn.urlopen(
> File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 638, in urlopen
> retries = retries.increment(method, url, error=e, _pool=self,
> File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 388, in increment
> raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /?hidden=111110&443=111111&beacon=111112&target=111113&atts=111114&mbname=111115&nocache=111116&promocodeaction=111117&ee=111118&number=111119&email=111110&page_type=111111&Soups=111112&fileEdit=111113&crt=111114&xml=111115&p=111116&msg1=111117&proxyurl=111118&page=111119&minutes=111120&pageid=111121 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)')))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/usr/local/bin/arjun", line 33, in
> sys.exit(load_entry_point('arjun==2.1.0', 'console_scripts', 'arjun')())
> File "/usr/local/lib/python3.8/site-packages/arjun-2.1.0-py3.8.egg/arjun/**main**.py", line 186, in main
> exporter(final_result)
> File "/usr/local/lib/python3.8/site-packages/arjun-2.1.0-py3.8.egg/arjun/core/exporter.py", line 57, in exporter
> burp_export(result)
> File "/usr/local/lib/python3.8/site-packages/arjun-2.1.0-py3.8.egg/arjun/core/exporter.py", line 24, in burp_export
> requests.get(url, params=populate(data['params']), headers=data['headers'])
> File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 76, in get
> return request('get', url, params=params, **kwargs)
> File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
> return session.request(method=method, url=url, **kwargs)
> File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
> resp = self.send(prep, **send_kwargs)
> File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
> r = adapter.send(request, **kwargs)
> File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
> raise SSLError(e, request=request)
> requests.exceptions.SSLError: HTTPSConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /?hidden=111110&443=111111&beacon=111112&target=111113&atts=111114&mbname=111115&nocache=111116&promocodeaction=111117&ee=111118&number=111119&email=111110&page_type=111111&Soups=111112&fileEdit=111113&crt=111114&xml=111115&p=111116&msg1=111117&proxyurl=111118&page=111119&minutes=111120&pageid=111121 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)')))

Mohammed, I got this too but I think it's because it needs Burp to be open and listening at the point the Arjun scan is ended - that's when it connects to Burp to dump the export. If you aren't listening in Burp at the point in time Arjun throws the error you're seeing. At least that's my understanding...

**Comment by s0md3v** [comment]
This issue has been fixed, thanks for reporting.

**Comment by r3l1c7** [comment]
Similiar issue

Strange error trying to get the output to burp.

arjun -u https://url.com/x.asp --stable -oB 127.0.0.1:8080

```
[✓] name: CardNo2, factor: param name reflection
[✓] name: CardNo1, factor: param name reflection
[✓] name: PhoneNo2, factor: param name reflection
[✓] name: PhoneNo1, factor: param name reflection
[✓] name: PurchaserLast, factor: param name reflection
[✓] name: SubscriberKanaFirst, factor: param name reflection
Traceback (most recent call last):
  File "/home/kali/.local/bin/arjun", line 8, in <module>
    sys.exit(main())
  File "/home/kali/.local/lib/python3.10/site-packages/arjun/__main__.py", line 190, in main
    exporter(final_result)
  File "/home/kali/.local/lib/python3.10/site-packages/arjun/core/exporter.py", line 59, in exporter
    burp_export(result)
  File "/home/kali/.local/lib/python3.10/site-packages/arjun/core/exporter.py", line 26, in burp_export
    requests.get(url, params=populate(data['params']), headers=data['headers'], proxies=proxies, verify=False)
  File "/home/kali/.local/lib/python3.10/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/kali/.local/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/kali/.local/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/kali/.local/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/kali/.local/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/kali/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "/home/kali/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "/home/kali/.local/lib/python3.10/site-packages/urllib3/connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "/home/kali/.local/lib/python3.10/site-packages/urllib3/connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "/home/kali/.local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "/home/kali/.local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "/usr/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1027, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname
```
