### ISSUE TITLE
what is a wrong?

### ISSUE THREAD

**Issue by zicohip** [s0md3v/Arjun#161]
###what wrong?
[*] Logicforcing the URL endpoint
Traceback (most recent call last):
  File "/usr/local/bin/arjun", line 33, in <module>
    sys.exit(load_entry_point('arjun==2.1.5', 'console_scripts', 'arjun')())
  File "/usr/local/lib/python3.9/dist-packages/arjun-2.1.5-py3.9.egg/arjun/__main__.py", line 190, in main
    exporter(final_result)
  File "/usr/local/lib/python3.9/dist-packages/arjun-2.1.5-py3.9.egg/arjun/core/exporter.py", line 55, in exporter
    json_export(result)
  File "/usr/local/lib/python3.9/dist-packages/arjun-2.1.5-py3.9.egg/arjun/core/exporter.py", line 13, in json_export
    with open(mem.var['json_file'], 'w+', encoding='utf8') as json_output:
FileNotFoundError: [Errno 2] No such file or directory: 'data/result.json'
![image](https://user-images.githubusercontent.com/76248189/167319142-59477299-5052-41df-b3d1-67eb78ed8b37.png)

**Comment by r3l1c7** [comment]
try, /data/result.json with the slash in the front

**Comment by s0md3v** [comment]
That's not a valid path, try what @r3l1c7 said.
