### ISSUE TITLE
ValueError: dictionary update sequence element #0 has length 1; 2 is required

### ISSUE THREAD

**Issue by big-ppp** [s0md3v/Arjun#163]
I am running the latest version, also tried previous, and keep getting the below error message after running for a while?

Traceback (most recent call last):
  File "/usr/local/bin/arjun", line 33, in <module>
    sys.exit(load_entry_point('arjun==2.1.0', 'console_scripts', 'arjun')())
  File "/Library/Python/3.8/site-packages/arjun-2.1.0-py3.8.egg/arjun/__main__.py", line 175, in main
    these_params = initialize(each, list(wordlist))
  File "/Library/Python/3.8/site-packages/arjun-2.1.0-py3.8.egg/arjun/__main__.py", line 117, in initialize
    response_1 = requester(request, {fuzz: fuzz[::-1]})
  File "/Library/Python/3.8/site-packages/arjun-2.1.0-py3.8.egg/arjun/core/requester.py", line 19, in requester
    payload.update(request['include'])
ValueError: dictionary update sequence element #0 has length 1; 2 is required

Any suggestions, thanks

**Comment by s0md3v** [comment]
This issue has been fixed in Arjun 2.1.6 🎉

Thanks for reporting!
