### ISSUE TITLE
-oB error

### ISSUE THREAD

**Issue by Phoenix1112** [s0md3v/Arjun#181]
i am using arjun with burp suite.. but my ip adress 192.168.1.104

arjun command:
------------------

```
arjun -i urls.txt -oB 192.168.1.104:8080
```

i have this error

```
Traceback (most recent call last):
  File "/usr/local/bin/arjun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/arjun/__main__.py", line 209, in main
    exporter(final_result)
  File "/usr/local/lib/python3.8/dist-packages/arjun/core/exporter.py", line 59, in exporter
    burp_export(result)
  File "/usr/local/lib/python3.8/dist-packages/arjun/core/exporter.py", line 26, in burp_export
    requests.get(url, params=populate(data['params']), headers=data['headers'], proxies=proxies, verify=False)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 458, in send
    raise InvalidURL(e, request=request)
requests.exceptions.InvalidURL: Failed to parse: https://127.0.0.1:192.168.1.104:8080
```

**Comment by JM-Lemmi** [comment]
the `-oB` Arguments expects only a portnumber, not an IP-Address and Portnumber. This can be seen in the last line of your error: Arjun tries to contact `https://127.0.0.1:192.168.1.104:8080`, which is not a valid address.

**Comment by ArkaprabhaChakraborty** [comment]
Would be happy to help with this and other issues as well :) @s0md3v

**Comment by ruevaughn** [comment]
@ArkaprabhaChakraborty It looks like he actively merge pull requests https://github.com/s0md3v/Arjun/pulls?q=is%3Apr+is%3Aclosed so if you want to contribute I would fork the repo, make your changes and then submit a pull request, he maintains a lot of  tools so i'm sure he would appreciate it

**Comment by JM-Lemmi** [comment]
I already wanted to add a generalized proxy flag (that also works for Burp on a different IP), but the PR was denied (https://github.com/s0md3v/Arjun/pull/170), because you can also set the `HTTP_PROXY` env variable.

**Comment by BreakfastSerial** [comment]
In my current case, the flag `-oB`, or `-oB 127.0.0.1:8080` does not proxy anything. I needed to use the env variables. Arjung 2.2.6 via pip on Windows 10.
