### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by learnerboy88** [s0md3v/Arjun#195]
I am getting the error when running this command 
`arjun -i burpRequests -m JSON --headers "Authorization: Basic exampleheaderrunninghere" -oT arjun-result  --include='{"root":{"a":"b",$arjun$}}'`

Error:
```
Traceback (most recent call last):
  File "/home/kali/.local/bin/arjun", line 8, in <module>
    sys.exit(main())
  File "/home/kali/.local/lib/python3.8/site-packages/arjun/__main__.py", line 201, in main
    these_params = initialize(each, list(wordlist))
  File "/home/kali/.local/lib/python3.8/site-packages/arjun/__main__.py", line 121, in initialize
    response_1 = requester(request, {fuzz: fuzz[::-1]})
  File "/home/kali/.local/lib/python3.8/site-packages/arjun/core/requester.py", line 18, in requester
    if len(request.get('include', '')) != 0:
TypeError: object of type 'NoneType' has no len()
```

**Comment by s0md3v** [comment]
Fixed in the latest release.
