### ISSUE TITLE
TypeError: argument of type 'bool' is not iterable

### ISSUE THREAD

**Issue by Nishantbhagat57** [s0md3v/Arjun#216]
```
[*] Scanning 20/187: https://abc.xyz.com/ja_jp/consider/okinawa/destination
[*] Probing the target for stability
Traceback (most recent call last):
  File "/usr/local/bin/arjun", line 11, in <module>
    load_entry_point('arjun==2.2.6', 'console_scripts', 'arjun')()
  File "/usr/local/lib/python3.8/dist-packages/arjun-2.2.6-py3.8.egg/arjun/__main__.py", line 215, in main
    these_params = initialize(each, list(wordlist))
  File "/usr/local/lib/python3.8/dist-packages/arjun-2.2.6-py3.8.egg/arjun/__main__.py", line 139, in initialize
    reason = compare(response_3, factors, {zzuf[:-1]: zzuf[::-1][:-1]})[2]
  File "/usr/local/lib/python3.8/dist-packages/arjun-2.2.6-py3.8.egg/arjun/core/anomaly.py", line 88, in compare
    if param not in factors['param_missing'] and re.search(r'[\'"\s]%s[\'"\s]' % re.escape(param), response.text):
TypeError: argument of type 'bool' is not iterable
```

@s0md3v Also it should skip the target if it gives error. Rn it just freezes.

**Comment by s0md3v** [comment]
Fixed in latest version v2.2.7.
