### ISSUE TITLE
Error execution

### ISSUE THREAD

**Issue by tXambe** [s0md3v/Arjun#217]
Hello,

when I run arjun I have the follow error:

```

arjun -u http://testphp.vulnweb.com
    _
   /_| _ '                                                                                                                                                                                     
  (  |/ /(//) v2.2.6                                                                                                                                                                           
      _/                                                                                                                                                                                       

Traceback (most recent call last):
  File "/usr/bin/arjun", line 33, in <module>
    sys.exit(load_entry_point('arjun==2.2.6', 'console_scripts', 'arjun')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/arjun", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/arjun/__main__.py", line 90, in <module>
    from arjun.core.requester import requester
  File "/usr/lib/python3/dist-packages/arjun/core/requester.py", line 9, in <module>
    from ratelimit import limits, sleep_and_retry
ModuleNotFoundError: No module named 'ratelimit'
```
A greeting and thanks

**Comment by ngha7** [comment]
As per the error output, you have to install the ratelimit module: pip install ratelimit
