### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'status_code'

### ISSUE THREAD

**Issue by gildasio** [s0md3v/Arjun#218]
I'm running Arjun in an application but got this bug result:

![image](https://github.com/user-attachments/assets/b21659d6-f5d0-4a40-80e9-10b9a29a58a7)

**Comment by Xitro01** [comment]
Hi @gildasio I'm using your fix now and it seems to have fixed this error.
But I have another error as well quite often:
```
[*] Probing the target for stability
Traceback (most recent call last):
  File "/home/kali/.local/bin/arjun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/kali/.local/lib/python3.12/site-packages/arjun/__main__.py", line 204, in main
    these_params = initialize(request, wordlist, single_url=is_single)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.12/site-packages/arjun/__main__.py", line 133, in initialize
    mem.var['healthy_url'] = response_1.status_code not in (400, 413, 418, 429, 503)
                             ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'status_code'
```
You seem to have a better understanding of what is going on. Could you have a look?

Thanks!

**Comment by gildasio** [comment]
Hi @Xitro01 ,

It seems that `requester()` returns a string for the URL you provided:

```
response_1 = requester(request, {fuzz[:-1]: fuzz[::-1][:-1]})
mem.var['healthy_url'] = response_1.status_code not in (400, 413, 418, 429, 503)
```

This way, there is no `status_code` member in `response_1`. In addition to other possibilities, such a thing can happen mainly because an exception was raised:

```
def requester(request, payload={}):
...
    except Exception as e:
        return str(e)
```

If it's ok for you, please provide an URL where this is happening so I can debug it and make a properly PR.

**Comment by Xitro01** [comment]
> Hi @Xitro01 ,
> 
> It seems that `requester()` returns a string for the URL you provided:
> 
> ```
> response_1 = requester(request, {fuzz[:-1]: fuzz[::-1][:-1]})
> mem.var['healthy_url'] = response_1.status_code not in (400, 413, 418, 429, 503)
> ```
> 
> This way, there is no `status_code` member in `response_1`. In addition to other possibilities, such a thing can happen mainly because an exception was raised:
> 
> ```
> def requester(request, payload={}):
> ...
>     except Exception as e:
>         return str(e)
> ```
> 
> If it's ok for you, please provide an URL where this is happening so I can debug it and make a properly PR.

Thanks for your response!

It actually is really random, so if I use -m GET/POST/JSON with a big list it isn't crashing on a specific URL, but it just does after a while. Sometimes it gets quite far, the other time it crashes somewhere in the beginning.

What I did see, is that -m XML crashes on most URLs and the error seems to be the exact same thing:
```
Traceback (most recent call last):
  File "/usr/local/bin/arjun", line 33, in <module>
    sys.exit(load_entry_point('arjun==2.2.7', 'console_scripts', 'arjun')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.12/site-packages/arjun/__main__.py", line 204, in main
    these_params = initialize(request, wordlist, single_url=is_single)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.12/site-packages/arjun/__main__.py", line 133, in initialize
    mem.var['healthy_url'] = response_1.status_code not in (400, 413, 418, 429, 503)
                             ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'status_code'
```

You could try the following command and see for yourself:
`arjun -u https://api.vishavideo.com/visha/api/feedback/query -m XML`

**Comment by gildasio** [comment]
Hey @Xitro01 ,

Sorry I miss this thread before.
Since it was closed by #219, if this error stills happens to your, please open a new issue (you can mention me there so I can get notified and dedicate a time to it :) )
