### ISSUE TITLE
Arjun often crashes on a list of URLs

### ISSUE THREAD

**Issue by Xitro01** [s0md3v/Arjun#223]
Somehow Arjun crashes quite often with the following error:
```
[*] Probing the target for stability
Traceback (most recent call last):
  File "/home/kali/.local/bin/arjun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/kali/.local/lib/python3.12/site-packages/arjun/__main__.py", line 204, in main
    these_params = initialize(request, wordlist, single_url=is_single)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.12/site-packages/arjun/__main__.py", line 133, in initialize
    mem.var['healthy_url'] = response_1.status_code not in (400, 413, 418, 429, 503)
                             ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'status_code'
```

I'm using the following command:
arjun -i gospider_deduped.txt -t 10 --disable-redirects -oT arjun.txt

The file contained 435 lines.
Running Arjun version: v2.2.7

Any idea?

**Comment by Xitro01** [comment]
The second error I got seems related to: https://github.com/s0md3v/Arjun/issues/218
The first one is different.

**Comment by Xitro01** [comment]
[225 ](https://github.com/s0md3v/Arjun/pull/225) seems to fix this

**Comment by ocervell** [comment]
Encountering the same issue on 2.2.7:

```
[*] Scanning 0/1: http://trade.ripio.com:8443

[*] Probing the target for stability

Traceback (most recent call last):

File "/root/.local/bin/arjun", line 7, in <module>

sys.exit(main())

^^^^^^

File "/root/.local/share/pipx/venvs/arjun/lib/python3.12/site-packages/arjun/__main__.py", line 204, in main

these_params = initialize(request, wordlist, single_url=is_single)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/share/pipx/venvs/arjun/lib/python3.12/site-packages/arjun/__main__.py", line 135, in initialize

print('%s Target returned HTTP %i, this may cause problems.' % (bad, request.status_code))

^^^^^^^^^^^^^^^^^^^

AttributeError: 'dict' object has no attribute 'status_code'[ERR] Command failed with return code 1

Last stdout lines:

^^^^^^^^^^^^^^^^^^^

AttributeError: 'dict' object has no attribute 'status_code'
```

Can you release a new version on PyPI with the above-mentioned fix ?
