### ISSUE TITLE
getting exception url error

### ISSUE THREAD

**Issue by awesomeaakash** [s0md3v/Arjun#28]
Hey Somdev brother, I am getting following error

> python3 arjun.py -u https://www.caviar.com/ --get

    _         
   /_| _ '    
  (  |/ /(//) v1.3
      _/      
[~] Analysing the content of the webpage
[~] Now lets see how target deals with a non-existent parameter
[!] Reflections: 4
[!] Response Code: 200
[!] Content Length: 49313
[!] Plain-text Length: 18667
[~] Parsing webpage for potential parameters
[+] Heuristic found a potential parameter: username
[+] Prioritizing it
[+] Heuristic found a potential parameter: password
[+] Prioritizing it
[+] Heuristic found a potential parameter: _wpnonce
[+] Prioritizing it
[+] Heuristic found a potential parameter: _wp_http_referer
[+] Prioritizing it
[+] Heuristic found a potential parameter: login
[+] Prioritizing it
[+] Heuristic found a potential parameter: rememberme
[+] Prioritizing it
[+] Heuristic found a potential parameter: email
[+] Prioritizing it
[+] Heuristic found a potential parameter: email_2
[+] Prioritizing it
[+] Heuristic found a potential parameter: mailchimp_woocommerce_newsletter
[+] Prioritizing it
[+] Heuristic found a potential parameter: register
[+] Prioritizing it
[+] Heuristic found a potential parameter: EMAIL
[+] Prioritizing it
[+] Heuristic found a potential parameter: b_eccdcccded66e9f05a10d41a2_14f0b2626c
[+] Prioritizing it
[+] Heuristic found a potential parameter: s
[+] Prioritizing it
[+] Heuristic found a potential parameter: post_type
[+] Prioritizing it
[~] Performing heuristic level checks
Traceback (most recent call last):
  File "arjun.py", line 183, in <module>
    toBeChecked = narrower(toBeChecked)
  File "arjun.py", line 174, in narrower
    if result.result():
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "arjun.py", line 136, in quickBruter
    newResponse = requester(url, joiner(params, include), headers, GET, delay)
  File "/opt/tools/Arjun/core/requester.py", line 17, in requester
    response = requests.get(url, params=data, headers=headers, verify=False)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 644, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 644, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 222, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 410, in send
    conn = self.get_connection(request.url, proxies)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 314, in get_connection
    conn = self.poolmanager.connection_from_url(url)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py", line 279, in connection_from_url
    pool_kwargs=pool_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py", line 218, in connection_from_host
    raise LocationValueError("No host specified.")
urllib3.exceptions.LocationValueError: No host specified.

>

**Comment by s0md3v** [comment]
I am unable to reproduce the issue. The specified website leads to a 403 forbidden access page which suggests that the server is blocking entire ranges of IP addresses based on region.
That explains why it happened.
