### ISSUE TITLE
Scanning reading from a file

### ISSUE THREAD

**Issue by gbiagomba** [s0md3v/Arjun#38]
Hello,

Below is the output i received when scanning from a target file. The file had 436 addresses in it. 

```
python3 arjun.py --urls /opt/Sublist3r/example_output.txt -t 25
    _         
   /_| _ '    
  (  |/ /(//) v1.6
      _/      

[~] Scanning: www.example.com
[~] Analysing the content of the webpage
[~] Analysing behaviour for a non-existent parameter
[!] Reflections: 1
[!] Response Code: 403
[!] Content Length: 386
[!] Plain-text Length: 320
[~] Parsing webpage for potential parameters
[~] Performing heuristic level checks
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/contrib/pyopenssl.py", line 453, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1640, in _raise_ssl_error
    raise SysCallError(-1, "Unexpected EOF")
OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/contrib/pyopenssl.py", line 459, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.example.com', port=443): Max retries exceeded with url: /?ngd=823658&nge=513850&ngf=919109&ngg=556475&ngh=891278&ngi=085140&ngj=787745&ngk=895942&ngl=342566&ngm=593508&ngn=720103&ngo=119027&ngp=324273&ngq=604840&ngr=413635&ngs=807938&ngt=338034&ngu=658367&ngv=472298&ngw=881795&ngx=388182&ngy=773095&ngz=662071&nh=031686&nha=488481&nhb=911366&nhc=074080&nhd=214385&nhe=289926&nhf=655834&nhg=824020&nhh=923376&nhi=526392&nhj=907304&nhk=988527&nhl=402676&nhm=375201&nhn=167334&nho=178807&nhp=748434&nhq=375429&nhr=093398&nhs=666865&nht=858836&nhu=179946&nhv=760124&nhw=643403&nhx=239654&nhy=640813&nhz=203072&ni=599959&nia=705022&nib=770501&nic=824025&nick=710193&NICK=460823&nickname=327265&nid=597483&nID=017862&nie=254182&nif=842625&nig=441040&nih=555816&nii=845795&nij=950130&nik=174546&nil=714814&nim=877190&nin=111767&nio=634869&nip=738078&niq=649969&nir=325424&nis=065515&nit=171309&niu=288568&niv=977452&nivoslider4wp_animSpeed=334654&nivoslider4wp_backgroundCaption=837956&nivoslider4wp_captionOpacity=320037&nivoslider4wp_colorCaption=076423&nivoslider4wp_colsBox=336234&nivoslider4wp_controlNav=968952&nivoslider4wp_directionNav=790816&nivoslider4wp_directionNavHide=940833&nivoslider4wp_effect=474707&nivoslider4wp_file_id=017060&nivoslider4wp_file_text_headline=431210&nivoslider4wp_file_type=411049&nivoslider4wp_height=279929&nivoslider4wp_image_link=063366&nivoslider4wp_imageQuality=903696&nivoslider4wp_js=916074&nivoslider4wp_keyboardNav=276467&nivoslider4wp_manualAdvance=698156&nivoslider4wp_pauseOnHover=556000&nivoslider4wp_pauseTime=782926&nivoslider4wp_rowsBox=817627&nivoslider4wp_width=378919&niw=407163&nix=516910&niy=460171&niz=803962&nj=043810&nja=223492&njb=589457&njc=005415&njd=652608&nje=513282&njf=532035&njfontcolor=592605&njform=115100&njg=933039&njh=641238&nji=646266&njj=835145&njk=514396&njl=347244&njlowercolor=588531&njm=743297&njn=660313&njo=331995&njp=324578&njq=004989&njr=005506&njs=903786&njt=751920&nju=042433&njv=798297&njw=315356 (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "arjun.py", line 245, in <module>
    finalResult[url] = initialize(url, include, headers, GET, delay, list(paramList), threadCount)
  File "arjun.py", line 210, in initialize
    toBeChecked = narrower(toBeChecked, url, include, headers, GET, delay, originalResponse, originalCode, reflections, factors, threadCount)
  File "arjun.py", line 160, in narrower
    if result.result():
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "arjun.py", line 133, in quickBruter
    newResponse = requester(url, joined, headers, GET, delay)
  File "/opt/Arjun/core/requester.py", line 20, in requester
    response = requests.get(url, params=data, headers=headers, verify=False)
  File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 659, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 659, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 238, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.example.com', port=443): Max retries exceeded with url: /?ngd=823658&nge=513850&ngf=919109&ngg=556475&ngh=891278&ngi=085140&ngj=787745&ngk=895942&ngl=342566&ngm=593508&ngn=720103&ngo=119027&ngp=324273&ngq=604840&ngr=413635&ngs=807938&ngt=338034&ngu=658367&ngv=472298&ngw=881795&ngx=388182&ngy=773095&ngz=662071&nh=031686&nha=488481&nhb=911366&nhc=074080&nhd=214385&nhe=289926&nhf=655834&nhg=824020&nhh=923376&nhi=526392&nhj=907304&nhk=988527&nhl=402676&nhm=375201&nhn=167334&nho=178807&nhp=748434&nhq=375429&nhr=093398&nhs=666865&nht=858836&nhu=179946&nhv=760124&nhw=643403&nhx=239654&nhy=640813&nhz=203072&ni=599959&nia=705022&nib=770501&nic=824025&nick=710193&NICK=460823&nickname=327265&nid=597483&nID=017862&nie=254182&nif=842625&nig=441040&nih=555816&nii=845795&nij=950130&nik=174546&nil=714814&nim=877190&nin=111767&nio=634869&nip=738078&niq=649969&nir=325424&nis=065515&nit=171309&niu=288568&niv=977452&nivoslider4wp_animSpeed=334654&nivoslider4wp_backgroundCaption=837956&nivoslider4wp_captionOpacity=320037&nivoslider4wp_colorCaption=076423&nivoslider4wp_colsBox=336234&nivoslider4wp_controlNav=968952&nivoslider4wp_directionNav=790816&nivoslider4wp_directionNavHide=940833&nivoslider4wp_effect=474707&nivoslider4wp_file_id=017060&nivoslider4wp_file_text_headline=431210&nivoslider4wp_file_type=411049&nivoslider4wp_height=279929&nivoslider4wp_image_link=063366&nivoslider4wp_imageQuality=903696&nivoslider4wp_js=916074&nivoslider4wp_keyboardNav=276467&nivoslider4wp_manualAdvance=698156&nivoslider4wp_pauseOnHover=556000&nivoslider4wp_pauseTime=782926&nivoslider4wp_rowsBox=817627&nivoslider4wp_width=378919&niw=407163&nix=516910&niy=460171&niz=803962&nj=043810&nja=223492&njb=589457&njc=005415&njd=652608&nje=513282&njf=532035&njfontcolor=592605&njform=115100&njg=933039&njh=641238&nji=646266&njj=835145&njk=514396&njl=347244&njlowercolor=588531&njm=743297&njn=660313&njo=331995&njp=324578&njq=004989&njr=005506&njs=903786&njt=751920&nju=042433&njv=798297&njw=315356 (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
```

**Comment by gbiagomba** [comment]
I did some debugging it and it seems the issue is with the thread flag but when i removed the flag it got further but then crashed again.

**Comment by ParikhKadam** [comment]
@s0md3v Making a pool of 50 is good. But have you considered URL length limit in a GET request?

**Comment by gbiagomba** [comment]
this seems to be fixed, closing the ticket
