### ISSUE TITLE
Script Broke in Between

### ISSUE THREAD

**Issue by gauravnarwani97** [s0md3v/Arjun#59]
I started to test a site and provided the url, it started well ut suddenly broke in between. I can't go far with this URL. Works properly another urls. Having an issue with a particular URL only.

    _
   /_| _ '
  (  |/ /(//) v1.6
      _/

[~] Analysing the content of the webpage
[~] Analysing behaviour for a non-existent parameter
[!] Reflections: 0
[!] Response Code: 200
[!] Content Length: 31636
[!] Plain-text Length: 13785
[~] Parsing webpage for potential parameters
[+] Heuristic found a potential GET parameter: collectionId
[!] Prioritizing it
[+] Heuristic found a potential GET parameter: query
[!] Prioritizing it
[+] Heuristic found a potential GET parameter: name
[!] Prioritizing it
[+] Heuristic found a potential GET parameter: email
[!] Prioritizing it
[+] Heuristic found a potential GET parameter: phone
[!] Prioritizing it
[+] Heuristic found a potential GET parameter: subject
[!] Prioritizing it
[+] Heuristic found a potential GET parameter: upload
[!] Prioritizing it
[+] Heuristic found a potential parameter: e
[!] Prioritizing it
[+] Heuristic found a potential parameter: e
[!] Prioritizing it
[+] Heuristic found a potential parameter: g
[!] Prioritizing it
[~] Performing heuristic level checks
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 543, in _updat                              e_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b'\r\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 302, in _error                              _catcher
    yield
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 598, in read_c                              hunked
    self._update_chunk_length()
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 547, in _updat                              e_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(2 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 745, in generat                              e
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 432, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 626, in read_c                              hunked
    self._original_response.close()
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 320, in _error                              _catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(2 bytes re                              ad)', IncompleteRead(2 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "arjun.py", line 237, in <module>
    finalResult[url] = initialize(url, include, headers, GET, delay, paramList,                               threadCount)
  File "arjun.py", line 211, in initialize
    toBeChecked = narrower(toBeChecked, url, include, headers, GET, delay, origi                              nalResponse, originalCode, reflections, factors, threadCount)
  File "arjun.py", line 161, in narrower
    if result.result():
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_resu                              lt
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "arjun.py", line 134, in quickBruter
    newResponse = requester(url, joined, headers, GET, delay)
  File "/root/tools/Arjun/core/requester.py", line 20, in requester
    response = requests.get(url, params=data, headers=headers, verify=False)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in reque                              st
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 670, in send
    r.content
  File "/usr/lib/python3/dist-packages/requests/models.py", line 823, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes                              ()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 748, in generat                              e
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(2                               bytes read)', IncompleteRead(2 bytes read))

**Comment by balook** [comment]
same problem

**Comment by n4vn337** [comment]
yep same problem, cant find any solution anywhere... 👎

**Comment by s0md3v** [comment]
Fixed.
