### ISSUE TITLE
UnboundLocalError: local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by ptrk01** [s0md3v/Arjun#62]
From time to time, I get the following error and the program quits. It has occurred a couple of times over the past weeks. It seems it does not depend on a specific url because I tested one url a couple of times and one time arjun runs without problems and next time it throws this error.

`Traceback (most recent call last):
  File "arjun.py", line 267, in <module>
    finalResult[url] = initialize(url, include, headers, GET, delay, list(paramList), threadCount)
  File "arjun.py", line 211, in initialize
    toBeChecked = narrower(toBeChecked, url, include, headers, GET, delay, originalResponse, originalCode, reflections, factors, threadCount)
  File "arjun.py", line 161, in narrower
    if result.result():
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "arjun.py", line 134, in quickBruter
    newResponse = requester(url, joined, headers, GET, delay)
  File "/home/tools/arjun/core/requester.py", line 28, in requester
    return response
UnboundLocalError: local variable 'response' referenced before assignment
`

**Comment by s0md3v** [comment]
Potentially fixed. Closing until it's reproduced.
