### ISSUE TITLE
Error name 'source_1' is not defined

### ISSUE THREAD

**Issue by amirnsahmad** [s0md3v/Arjun#85]
When i try use the following command, i got the error:

python3 arjun.py -u https://www.google.com/

Traceback (most recent call last):
  File "arjun.py", line 167, in <module>
    these_params = initialize(request, wordlist)
  File "arjun.py", line 132, in initialize
    factors = define(response_1, response_2, fuzz, fuzz[::-1], wordlist)
  File "core/anamoly.py", line 46, in define
    factors['lines_diff'] = diff_map(response_1, response_2)
  File "core/anamoly.py", line 5, in diff_map
    lines_1, lines_2 = source_1.split('\n'), source_2.split('\n')
NameError: name 'source_1' is not defined

**Comment by s0md3v** [comment]
This has been fixed in the latest commit. Thanks for reporting.
