### ISSUE TITLE
KeyError: 'include'

### ISSUE THREAD

**Issue by z3dc0ps** [s0md3v/Arjun#86]
Traceback (most recent call last):
  File "arjun.py", line 179, in <module>
    these_params = initialize(each, list(wordlist))
  File "arjun.py", line 126, in initialize
    response_1 = requester(request, {fuzz : fuzz[::-1]})
  File "/root/Desktop/bug/subdomain/run/Arjun/core/requester.py", line 15, in requester
    if request['include']:
KeyError: 'include'
![1](https://user-images.githubusercontent.com/61974788/101285200-edc67700-3809-11eb-8fee-59594d32c078.PNG)

**Comment by s0md3v** [comment]
This has been fixed in the latest commit. Thanks for reporting.
